export const MOCK_USER = {
  _id: 'user_1',
  name: 'Sagar Thapa',
  email: 'sagar@example.com',
  role: 'both',
  phone: '9841234567',
  district: 'Kathmandu',
  grade: 'bachelor_2',
  reputation: 4.7,
  totalRatings: 23,
  isVerified: true,
  avatar: null,
  location: { lat: 27.7172, lng: 85.324 },
  createdAt: '2025-08-15T10:00:00Z',
}

export const MOCK_BOOKS = [
  {
    _id: 'book_1',
    title: 'Engineering Mathematics I',
    author: 'Dr. Ram Sharma',
    isbn: '978-9937-1234-01',
    category: 'engineering',
    grade: 'bachelor_1',
    condition: 'good',
    listingType: 'sell',
    price: 450,
    description: 'Well-maintained engineering math textbook with minimal highlighting. Perfect for first-year students.',
    keywords: ['calculus', 'engineering', 'math', 'first year'],
    images: [],
    seller: {
      _id: 'user_2',
      name: 'Anita Karki',
      reputation: 4.9,
      district: 'Lalitpur',
      location: { lat: 27.6588, lng: 85.3247 },
    },
    distance: 2.3,
    recommendationScore: 92,
    recommendationFactors: {
      titleMatch: true,
      keywordMatch: true,
      gradeMatch: true,
      nearbySeller: true,
      reputation: true,
    },
    status: 'active',
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    _id: 'book_2',
    title: 'Principles of Physics',
    author: 'Halliday & Resnick',
    isbn: '978-9937-1234-02',
    category: 'science',
    grade: 'bachelor_1',
    condition: 'like_new',
    listingType: 'sell',
    price: 800,
    description: 'International edition, barely used. No markings or damage.',
    keywords: ['physics', 'mechanics', 'science'],
    images: [],
    seller: {
      _id: 'user_3',
      name: 'Bikash Rai',
      reputation: 4.5,
      district: 'Kathmandu',
      location: { lat: 27.7103, lng: 85.3222 },
    },
    distance: 1.1,
    recommendationScore: 85,
    recommendationFactors: {
      titleMatch: true,
      keywordMatch: false,
      gradeMatch: true,
      nearbySeller: true,
      reputation: false,
    },
    status: 'active',
    createdAt: '2026-01-08T14:00:00Z',
  },
  {
    _id: 'book_3',
    title: 'Organic Chemistry',
    author: 'Morrison & Boyd',
    isbn: '978-9937-1234-03',
    category: 'science',
    grade: 'bachelor_2',
    condition: 'fair',
    listingType: 'exchange',
    price: 0,
    description: 'Looking to exchange for Physical Chemistry or Biochemistry textbook.',
    keywords: ['chemistry', 'organic', 'science'],
    images: [],
    seller: {
      _id: 'user_4',
      name: 'Priya Shrestha',
      reputation: 4.8,
      district: 'Bhaktapur',
      location: { lat: 27.671, lng: 85.4298 },
    },
    distance: 4.8,
    recommendationScore: 78,
    recommendationFactors: {
      titleMatch: false,
      keywordMatch: true,
      gradeMatch: true,
      nearbySeller: true,
      reputation: true,
    },
    status: 'active',
    createdAt: '2026-01-05T11:00:00Z',
  },
  {
    _id: 'book_4',
    title: 'Business Statistics',
    author: 'Ken Black',
    isbn: '978-9937-1234-04',
    category: 'management',
    grade: 'bachelor_3',
    condition: 'good',
    listingType: 'sell',
    price: 350,
    description: 'Complete with all chapters. Some pencil notes in margins.',
    keywords: ['statistics', 'business', 'management', 'BBA'],
    images: [],
    seller: {
      _id: 'user_5',
      name: 'Rohan Gurung',
      reputation: 4.2,
      district: 'Kathmandu',
      location: { lat: 27.728, lng: 85.335 },
    },
    distance: 3.5,
    recommendationScore: 70,
    status: 'active',
    createdAt: '2026-01-02T09:00:00Z',
  },
  {
    _id: 'book_5',
    title: 'Introduction to Programming in C',
    author: 'Yashwant Kanetkar',
    isbn: '978-9937-1234-05',
    category: 'engineering',
    grade: 'bachelor_1',
    condition: 'new',
    listingType: 'donate',
    price: 0,
    description: 'Donating this book to help fellow students. Pick up from Patan area.',
    keywords: ['programming', 'C language', 'computer science'],
    images: [],
    seller: {
      _id: 'user_6',
      name: 'Sunita Tamang',
      reputation: 5.0,
      district: 'Lalitpur',
      location: { lat: 27.664, lng: 85.319 },
    },
    distance: 0.8,
    recommendationScore: 88,
    status: 'active',
    createdAt: '2025-12-28T16:00:00Z',
  },
  {
    _id: 'book_6',
    title: 'Nepali Sahitya Ko Itihas',
    author: 'Prof. Krishna Prasad',
    isbn: '978-9937-1234-06',
    category: 'language',
    grade: 'bachelor_2',
    condition: 'good',
    listingType: 'sell',
    price: 200,
    description: 'Nepali literature history book for TU syllabus.',
    keywords: ['nepali', 'literature', 'sahitya', 'TU'],
    images: [],
    seller: {
      _id: 'user_7',
      name: 'Maya Limbu',
      reputation: 4.6,
      district: 'Kathmandu',
      location: { lat: 27.705, lng: 85.31 },
    },
    distance: 2.0,
    recommendationScore: 65,
    status: 'active',
    createdAt: '2025-12-20T10:00:00Z',
  },
]

export const MOCK_REQUESTS = [
  {
    _id: 'req_1',
    book: MOCK_BOOKS[0],
    buyer: { _id: 'user_1', name: 'Sagar Thapa' },
    seller: MOCK_BOOKS[0].seller,
    status: 'pending',
    message: 'Hi, is this book still available?',
    createdAt: '2026-01-12T10:00:00Z',
  },
  {
    _id: 'req_2',
    book: MOCK_BOOKS[1],
    buyer: { _id: 'user_1', name: 'Sagar Thapa' },
    seller: MOCK_BOOKS[1].seller,
    status: 'payment_pending',
    message: 'I would like to buy this book.',
    paymentMethod: 'esewa',
    createdAt: '2026-01-10T14:00:00Z',
  },
  {
    _id: 'req_3',
    book: MOCK_BOOKS[4],
    buyer: { _id: 'user_8', name: 'Nabin KC' },
    seller: MOCK_BOOKS[4].seller,
    status: 'completed',
    message: 'Thank you for donating!',
    createdAt: '2026-01-05T09:00:00Z',
  },
]

export const MOCK_NOTIFICATIONS = [
  {
    _id: 'notif_1',
    type: 'request',
    title: 'New Book Request',
    message: 'Sagar Thapa requested your book "Engineering Mathematics I".',
    read: false,
    requestId: 'req_1',
    bookId: 'book_1',
    createdAt: '2026-01-12T10:00:00Z',
  },
  {
    _id: 'notif_2',
    type: 'payment',
    title: 'Payment Uploaded',
    message: 'Buyer uploaded payment proof for "Principles of Physics".',
    read: false,
    requestId: 'req_2',
    transactionId: 'req_2',
    createdAt: '2026-01-11T15:00:00Z',
  },
  {
    _id: 'notif_3',
    type: 'recommendation',
    title: 'New Recommendations',
    message: 'We found 3 books matching your search for "calculus".',
    read: true,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    _id: 'notif_4',
    type: 'rating',
    title: 'New Rating Received',
    message: 'You received a 5-star rating from Nabin KC.',
    read: true,
    createdAt: '2026-01-08T12:00:00Z',
  },
]

export const MOCK_SELLERS = MOCK_BOOKS.map((book) => ({
  ...book.seller,
  activeListings: Math.floor(Math.random() * 5) + 1,
  bookTitle: book.title,
}))

export const MOCK_DASHBOARD_STATS = {
  totalListings: 3,
  activeRequests: 2,
  completedDeals: 12,
  reputation: 4.7,
  unreadNotifications: 2,
}
